config/routes.rb
Rails.application.routes.draw do

  get 'events/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root                       'static_pages#index'
  get    'paradox_people' => 'static_pages#paradox_people'
  get    'uploads'        => 'static_pages#uploads'
  get    'paradox_news'   => 'static_pages#paradox_news'
  get    'about'          => 'static_pages#about'
  get    'tits'           => 'static_pages#tits'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :taglines, :doxes, :titles, :people, :events, :blogposts do
    collection { post :import }
  end

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :admin_user,  only:[:destroy, :update, :patch, :new]

  def index
  	@blogposts = BlogPost.all
  end

  def show
  	@blogpost = BlogPost.find(params[:id])
  end

  def new
  	@blogpost = BlogPost.new
  end

  def edit
  	@blogpost = BlogPost.find(params[:id])
  end

  def create
  	@blogpost = BlogPost.new(blogpost_params)
 
  	if @blogpost.save
    	redirect_to blogpost_path(@blogpost.id)
  	else
    	render 'new'
  	end
  end

  def update
    @blogpost = BlogPost.find(params[:id])
 
    if @blogpost.update(blogpost_params)
      redirect_to blogpost_path(@blogpost.id)
    else
      render 'edit'
    end
  end

  def destroy
  	@blogpost = BlogPost.find(params[:id])
    @blogpost.destroy
    redirect_to blogposts_path
  end


 
  private
    def blogpost_params
      params.require(:blogpost).permit(:title, :text, :blog_index, :date, :category, :subcategory, :link, :picture)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/views/blogposts/edit.html.erb
<%= form_for :blogpost, url: blogpost_path, method: :patch do |f| %>
 
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blogpost.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @blogpost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  	<div class="col-md-4">
  	  <%= f.label :blog_index %>
  	  <%= f.text_field :blog_index, class: 'form-control' %>
  	</div>
  </div>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <div class="row">
    <div class="col-md-4">
      <%= f.label :category %>
      <%= f.text_field :category, class: 'form-control' %>
    </div>
	<div class="col-md-4">
	  <%= f.label :subcategory %>
	  <%= f.text_field :subcategory, class: 'form-control' %>
    </div>
    <div class="col-md-4">
	  <%= f.label :date %>
	  <%= f.text_field :date, class: 'form-control' %>
    </div>
  </div>

  <%= f.label :text %>
  <%= f.text_area :text, class: 'form-control', rows: 15 %>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control' %>
    </div>
	<div class="col-md-6">
	  <%= f.label :picture %>
	  <%= f.text_field :picture, class: 'form-control' %>
    </div>
  </div>

      <%= f.submit "Save", class: "btn btn-primary" %>
 
<% end %>
 <br>
<%= link_to 'Back', blogposts_path, class: "btn btn-primary" %>

app/views/blogposts/index.html.erb
<div class="container">
  <% @blogposts.each do |blogpost| %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="row">
    	  <h2 class="text-justify"><%= blogpost.title %></h2>
    	  <div class="row">
      		<div class="text-center" style="border-top: solid black 2px; border-bottom: solid black 2px; margin-bottom: 10px">
        	  <div class="h5"><%= blogpost.category %> &nbsp | &nbsp <%= blogpost.subcategory %> &nbsp | &nbsp <%= blogpost.date %></div>
      		</div> 
    	  </div>
    	  <div class="row">
      		<div class="col-md-12 text-center blog-pic">
        	  <%= cl_image_tag("Blog/" + blogpost.picture + ".png")%>
      		</div>
    	  </div>
    	  <div class="row">
      	    <div class="col-md-12 text-justify">
        	  <h4><%= blogpost.text.html_safe %></h4>
      	  	</div>
    	  </div>
        </div>
      </div>
    </div>
    
    <% if !current_user.nil? && current_user.admin? %>
      <div class="row admin-box">
        <div class="col-md-offset-8 col-md-4">
    	  <%= link_to "Edit", edit_blogpost_path(blogpost.id), :class => "btn btn-default" %>
		  <%= link_to "Delete", blogpost_path(blogpost), method: :delete, :class => "btn btn-default"%>
		  <%= link_to 'New post', new_blogpost_path, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/blogposts/new.html.erb
<%= form_for :blogpost, url: blogposts_path do |f| %>
 
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blogpost.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @blogpost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  	<div class="col-md-4">
  	  <%= f.label :blog_index %>
  	  <%= f.text_field :blog_index, class: 'form-control' %>
  	</div>
  </div>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <div class="row">
    <div class="col-md-4">
      <%= f.label :category %>
      <%= f.text_field :category, class: 'form-control' %>
    </div>
	<div class="col-md-4">
	  <%= f.label :subcategory %>
	  <%= f.text_field :subcategory, class: 'form-control' %>
    </div>
    <div class="col-md-4">
	  <%= f.label :date %>
	  <%= f.text_field :date, class: 'form-control' %>
    </div>
  </div>

  <%= f.label :text %>
  <%= f.text_area :text, class: 'form-control', rows: 15 %>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control' %>
    </div>
	<div class="col-md-6">
	  <%= f.label :picture %>
	  <%= f.text_field :picture, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Create new post", class: "btn btn-primary" %>
    
<% end %>

<br>

<%= link_to 'Cancel', blogposts_path, class: "btn btn-default" %>

app/views/blogposts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="row">
  	  <h2 class="text-justify"><%= @blogpost.title %></h2>
  	  <div class="row">
    		<div class="text-center" style="border-top: solid black 2px; border-bottom: solid black 2px; margin-bottom: 10px">
      	  <div class="h5"><%= @blogpost.category %> &nbsp | &nbsp <%= @blogpost.subcategory %> &nbsp | &nbsp <%= @blogpost.date %></div>
    		</div> 
  	  </div>
  	  <div class="row">
    		<div class="col-md-12 text-center blog-pic">
      	  <%= cl_image_tag("Blog/" + @blogpost.picture + ".png")%>
    		</div>
  	  </div>
  	  <div class="row">
    	    <div class="col-md-12 text-justify">
      	  <h4><%= @blogpost.text.html_safe %></h4>
    	  	</div>
  	  </div>
      </div>
    </div>
  </div>
  
  <!-- Admin controls -->
  <% if !current_user.nil? && current_user.admin? %>
    <div class="row admin-box">
      <div class="col-md-offset-8 col-md-4">
  	  <%= link_to "Edit", edit_blogpost_path(@blogpost.id), :class => "btn btn-default" %>
	  <%= link_to "Delete", blogpost_path(@blogpost), method: :delete, :class => "btn btn-default"%>
	  <%= link_to 'New post', new_blogpost_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>