config/routes.rb
Rails.application.routes.draw do

  get 'events/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root                       'static_pages#index'
  get    'paradox_people' => 'static_pages#paradox_people'
  get    'uploads'        => 'static_pages#uploads'
  get    'paradox_news'   => 'static_pages#paradox_news'
  get    'about'          => 'static_pages#about'
  get    'tits'           => 'static_pages#tits'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :taglines, :doxes, :titles, :people, :events, :blogposts do
    collection { post :import }
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'time'

  

  def index
    @today = Time.now

  	@taglines = Tagline.order("RANDOM()").limit(1000)
    @randomTaglines = Tagline.limit(120).order("RANDOM()").pluck(:title).to_a

    @releases = Title.where("release_month = ? and release_day = ?", Time.now.mon.to_i, Time.now.day.to_i)
    @births = Person.where("birth_month = ? and birth_day = ?", Time.now.mon.to_i, Time.now.day.to_i)
    @deaths = Person.where("death_month = ? and death_day = ?", Time.now.mon.to_i, Time.now.day.to_i)

    @montages = Vimeo::Simple::Album.videos("3931279")

    @tits = Title.none
    if !@releases.nil?
      @tits = @tits + @releases
    end

    if !@deaths.nil?
      @tits = @tits + @deaths
    end

    if !@births.nil?
      @tits = @tits + @births
    end

    @welcomeText = ["Your gateway to the 4th dimension...", "It's all in the mind, you know...",
                    "Your one stop for this sort of thing!", "Your Time Travel Agency...",
                    "If you’re confused and off-balance – you are home...", 
                    "Take a number.  We’ll be with you between now and eternity...",
                    "Your home for illusion, delusion, and confusion...", "Where infinity begins and ends...",
                    "The Land Beyond The Land Beyond...", "Where it’s always now, now...",
                    "Welcome to Never Say Never Land!", "Nowhere is now here!", 
                    "Just two blocks north of the middle of nowhere...", 
                    "Keep your hands outside the vehicle at all times", "Bridge Out (back in 15 minutes)"]
    
    

  end


  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/_tagline.html.erb
    <div class="row text-center">
      <h3>Which title below delivers this tagline?</h3>
    
      <div id="taglineCarousel" class="carousel slide" data-ride="carousel" data-interval="0">
        <div class="carousel-inner" role="listbox">
          <% @taglines.each_with_index do |tagline, index| %>
            <div class="item <% if index == 0 %> active <% end %>">
              <h3 style="max-width:700px; margin: 10px auto; min-height: 70px; font-style: italic"><%= tagline.tagline %></h3>
              <div class="multiple-choice-box">
                
                <% dup = [tagline.title]%>
                <% multipleChoice = (@randomTaglines - dup).sample(2) %>
                <% multipleChoice.push(tagline.title).shuffle.each do |choice| %>
                  <div class="row">
                    <% if choice == tagline.title %>

                      <div class="col-xs-1">
                        <div class="circle correct"></div>
                      </div>

                      <div class="col-xs-8">
                        <h4 class=" guess" style="display:inline">
                          <% if Title.find_by(title: choice).nil? %>
                            <%= choice %>
                          <% else %>
                            <%= link_to choice, title_path(Title.find_by(title: choice))%>
                          <% end %>
                        </h4>
                      </div>

                      <div class="col-xs-3">
                        <h4 class="correct-text" style="display:inline">CORRECT</h4><br>  
                      </div>

                    <% else %>

                      <div class="col-xs-1">
                        <div class="circle incorrect"></div>
                      </div>

                      <div class="col-xs-8">
                        <h4 class=" guess" style="display:inline">
                          <% if Title.find_by(title: choice).nil? %>
                            <%= choice %>
                          <% else %>
                            <%= link_to choice, title_path(Title.find_by(title: choice))%>
                          <% end %>
                        </h4>
                      </div>

                      <div class="col-xs-3">
                        <h4 class="incorrect-text" style="display:inline">BUMMER</h4><br>  
                      </div>

                    <% end %> <!-- End of Correct/Incorrect conditional -->
                  </div>
                <% end %>  <!-- End of Multiple Choice select -->
              </div>
            </div>
          <% end %> <!-- End of Tagline select -->
        </div>
      
        <!-- //////// Left and right Tagline controls ////////////-->

        <a class="left carousel-control" href="#taglineCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#taglineCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>  <!-- End of Carousel -->

      <h4>Your score: <span id="score">0</span></h4>
    </div> 

app/views/static_pages/_tit.html.erb
<div class="container-fluid">
<% if tit.has_attribute?(:title) %>
  <!-- EVENT IS A RELEASE -->

  <div class="row center">
    <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 tit-images">
      <% if tit.series_index.nil? || tit.series_index.blank? %>
        <%= link_to cl_image_tag("Titles/" + tit.title_index.to_s + ".png", :width => 300, :class => "tit-photo left-tit-image", :alt => tit.title, :default_image => "Titles:10000.png"), title_path(tit.id) %>
      <% else %>
        <%= link_to cl_image_tag("Titles/" + tit.series_index.to_s + ".png", :width => 300, :class => "tit-photo left-tit-image", :alt => tit.title, :default_image => "Titles:10000.png"), title_path(tit.id) %>
      <% end %>
      <!-- <%= image_tag "bubble.png", class: "bubble"%> -->
      <% titlePerson = Person.find_by people_index: tit.people_index %>

      <% if !titlePerson.nil? && titlePerson.has_audio? %>
        <% audioIndex = tit.people_index %>
        <div id="circle" class="audioButton" style="transform:scaleX(-1)">
          <%= image_tag "bubble.png", class: "bubble"%>
          <%= audio_tag "http://res.cloudinary.com/paradoxparkway/video/upload/ac_mp3/v1448471034/Audio/#{audioIndex}.mp3",
            class: "audio-play" %>
        </div>  
      <% end %>

      <!-- CHECK IF TITLE IS USING DEFAULT IMAGE FOR RELATED PERSON -->

      <% if tit.people_index == 40000 %>
        <%= link_to cl_image_tag("People/" + tit.people_index.to_s + ".png", :width => 300, :class=>"tit-photo right-tit-image", :default_image => "People:40000.png"), title_path(tit.id) %>
      <% else %>
        <% titlePerson = Person.find_by people_index: tit.people_index %>
        <%= link_to cl_image_tag("People/" + tit.people_index.to_s + ".png", :width => 300, :class=>"tit-photo right-tit-image", :default_image => "People:40000.png"), person_path(titlePerson.id) %>
      <% end %>
    </div>
    
  </div>

  <!-- CHECK TYPE OF RELEASE -->
  <div class="row center ">
    <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 tit-text">
      <div class="tit-textbox">
         
        <h4>On this day in <%= tit.release_year %>,
          <% if tit.sub_medium =~ /film/i %>
             "<%= link_to tit.title, title_path(tit.id) %>" first opened in theaters.
        
          <% elsif tit.sub_medium =~ /episode|comic/i %>
          season <%= tit.season_num %> of "<%= tit.title %>" episode <%= tit.episode_num %>: <i><%= link_to tit.episode, title_path(tit.id) %></i> was first broadcast.
        
          <% elsif tit.sub_medium =~ /tv series|tv miniseries|tv movie/i %>
            "<%= link_to tit.title, title_path(tit.id) %>" premiered.
        
          <% elsif tit.sub_medium =~ /book|novel|video game|video|short/i %>
            "<%= link_to tit.title, title_path(tit.id) %>" was released.
        
          <% end %>
        </h4>
      <!-- CHECK IF RELEASE MESSAGE EXISTS -->
      
        <% if tit.release_msg.nil? %>
          <h4> Message coming soon. </h4>

        <% else %>
          <h4> <%= tit.release_msg %> </h4>

        <% end %>
      </div>
    </div>
    <span class="col-3-sm"></span>
  </div>  

  <% else %> 
    <!-- EVENT IS A PERSON-->

    <div class="row center">
      <div class="col-sm-offset-1 col-sm-10  col-md-offset-2 col-md-8 tit-images">
        <%= link_to cl_image_tag("People/" + tit.people_index.to_s + ".png", :width => 300, :alt => tit.full_name, :class => "tit-photo left-tit-image", :default_image => "People:40000.png"), person_path(tit.id) %>

        <!-- IS THERE A SOUND FILE WITH THIS PERSON? -->

        <% if tit.has_audio? %>
          <% audioIndex = tit.people_index %>
          <div id="circle" class="audioButton">
            <%= image_tag "bubble.png", class: "bubble"%>
            <%= audio_tag "http://res.cloudinary.com/paradoxparkway/video/upload/ac_mp3/v1448471034/Audio/#{audioIndex}.mp3",
            class: "audio-play" %>
          </div>
        <% end %>

        <!-- NO TITLE ENTERED FOR THIS PERSON -->

        <% if tit.title_index == 10000 %>
          <%= link_to cl_image_tag("People/" + tit.people_index.to_s + ".png", :width => 300, :alt => tit.full_name, :class => "tit-photo right-tit-image", :default_image => "Titles:10000.png"), person_path(tit.id) %>

        <!-- LINK TO RELATED TITLE FOR THIS PERSON -->

        <% else %>
          <% personTitle = Title.find_by title_index: tit.title_index %>
          <%= link_to cl_image_tag("Titles/" + tit.title_index.to_s + ".png", :width => 300, :alt => personTitle.title, :class=>"tit-photo right-tit-image", :default_image => "People:40000.png"), title_path(personTitle.id) %>

        <% end %>

      </div>
    </div>                
    <!-- EVENT IS A BIRTH -->
    <% if tit.birth_month == Time.now.mon.to_i && tit.birth_day == Time.now.day.to_i %>

      <div class="row center">
        <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 tit-text">
          <div class="tit-textbox">
      
            <% if !tit.death_year.nil? %>
            <!-- PERSON WAS BORN TODAY BUT IS DEAD -->

              <h4><%= link_to tit.full_name, person_path(tit.id) %>, <%= tit.nationality %> <%= tit.profession %>, was born on this day in <%= tit.birth_year%> (and sadly passed away in <%= tit.death_year %>).
              </h4>

            <% else %>
            <!-- PERSON WAS BORN TODAY AND STILL ALIVE -->

              <h4>Happy <%=tit.age.ordinalize%> Birthday, <%= link_to tit.full_name, person_path(tit.id) %>!</h4>
              <h4><%= tit.full_name %>, <%= tit.nationality %> <%= tit.profession %>, was born on this day in <%= tit.birth_year%>.
              </h4>
            <% end %>

            <h5> <%= tit.travels %> </h5>
          </div>
        </div>
      </div>

    <% else %>
    <!-- EVENT IS A DEATH -->

      <div class="row center">
        <div class="col-sm-offset-3 col-sm-6 col-md-offset-2 col-md-8 tit-text">
          <div class="tit-textbox">
            <h4> <%= link_to tit.full_name, person_path(tit.id) %>, <%= tit.nationality %> <%=tit.profession %>, died on this day in <%= tit.death_year %> (and was born in <%= tit.birth_year %>).
            </h4>
            <h5> <%= tit.travels %> </h5>
          </div>
        </div>  
      </div>

    <% end %>

  <% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>

app/views/static_pages/events.html.erb
<% (Date.today..Date.today + 30.days).each do |date| %>
  <h3><%= date.strftime("%B #{date.day.ordinalize}")%></h3>
    <!-- All Titles for this date -->
    <h4>Titles</h4>
	<% Title.where("release_month = ? and release_day = ?", date.mon.to_i, date.day.to_i).each do |title| %>
	  <div class="event-entry">
	  	<div class="row">
	  	  <div class="col-xs-1">
	  	    <% if title.series_index.nil?%>
            <%= link_to cl_image_tag("Titles/" + title.title_index.to_s + ".png", :class => "event-index-photo", :alt => title.title,
                                                                                  :default_image => "Title:10000.png"), title_path(title.id) %>
          <% else %>
            <%= link_to cl_image_tag("Titles/" + title.series_index.to_s + ".png", :class => "event-index-photo", :alt => title.title,
                                                                                   :default_image => "Title:10000.png"), title_path(title.id) %>
          <% end %>
	  	  </div>
	  	  <div class="col-xs-1">
	  	    <%= cl_image_tag("People/" + title.people_index.to_s + ".png", :class=>"event-index-photo", :default_image => "People:40000.png") %>	
	  	  </div>
          <div class="col-xs-9 col-xs-offset-1">
      	    <strong>Title:</strong> <%= title.title%> | <strong>Title Index:</strong><%= title.title_index%> | 
      	    <strong>Series Index:</strong> <%= title.series_index%> | <strong>People Index:</strong> <%= title.people_index%> |  
      	    <strong>Release Date:</strong> <%= title.release_date%> | <strong><%= link_to "EDIT", edit_title_path(title.id) %></strong>
      	    <br>
      	    <!-- Is the release message missing? -->
            <% if title.release_msg.nil? %>
              <div style="color:orange"><strong>Release Message:</strong> <%= title.release_msg%></div>
            <% else %>
              <strong>Release Message:</strong> <%= title.release_msg%>
            <% end %>
          </div>
        </div>
	  </div>
	<% end %>
	<!-- All Births for this date -->
  <h4>Births</h4>
	<% Person.where("birth_month = ? and birth_day = ?", date.mon.to_i, date.day.to_i).each do |birth| %>
	  <div class="event-entry">
	  	<div class="row">
	  	  <div class="col-xs-1">
	  	    <%= cl_image_tag("People/" + birth.people_index.to_s + ".png", :class=>"event-index-photo", :default_image => "People:40000.png") %>	
	  	  </div>
	  	  <div class="col-xs-1">
	  	    <%= cl_image_tag("Titles/" + birth.title_index.to_s + ".png", :class=>"event-index-photo", :default_image => "Titles:10000.png") %>	
	  	  </div>
          <div class="col-xs-9 col-xs-offset-1">
      	    <strong>Name:</strong> <%= birth.full_name%> | <strong>People Index:</strong><%= birth.people_index%> | 
      	    <strong>Title Index:</strong> <%= birth.title_index%> | <strong>Birth Date:</strong> <%= birth.birth_date%> |
      	     <strong><%= link_to "EDIT", edit_person_path(birth.id) %></strong> 
          </div>
        </div>
	  </div>
	<% end %>
	<!-- All Deaths for this date -->
  <h4>Deaths</h4>
    <% Person.where("death_month = ? and death_day = ?", date.mon.to_i, date.day.to_i).each do |death| %>
	  <div class="event-entry">
	  	<div class="row">
	  	  <div class="col-xs-1">
	  	    <%= cl_image_tag("People/" + death.people_index.to_s + ".png", :class=>"event-index-photo", :default_image => "People:40000.png") %>	
	  	  </div>
	  	  <div class="col-xs-1">
	  	    <%= cl_image_tag("Titles/" + death.title_index.to_s + ".png", :class=>"event-index-photo", :default_image => "Titles:10000.png") %>	
	  	  </div>
          <div class="col-xs-9 col-xs-offset-1">
      	    <strong>Name:</strong> <%= death.full_name%> | <strong>People Index:</strong><%= death.people_index%> | 
      	    <strong>Title Index:</strong> <%= death.title_index%> | <strong>Death Date:</strong> <%= death.death_date%> |
      	     <strong><%= link_to "EDIT", edit_person_path(death.id) %></strong> 
          </div>
        </div>
	  </div>
	<% end %>
<% end %>

app/views/static_pages/index.html.erb
<div class="welcome-row center">
  <div class="nav-box">
    <div class="nav-left-buttons">

      <%= link_to "<h5>PARADOXES</h5>".html_safe, doxes_path,  class: "pp-button" %>

      <%= link_to "<h5>PEOPLE</h5>".html_safe,    people_path, class: "pp-button" %>

      <%= link_to "<h5>TITLES</h5>".html_safe,    titles_path, class: "pp-button" %>
      
    </div>

    <%= link_to image_tag("PPlogo.png", class: "logo-img", alt: "Paradox Parkway"), root_path%>  

    <div class="nav-right-buttons">

      <%= link_to "<h5>CONTACT</h5>".html_safe, contacts_path,  class: "pp-button" %>

      <%= link_to "<h5>BLOG</h5>".html_safe,    blogposts_path, class: "pp-button" %>

      <%= link_to "<h5>JOIN</h5>".html_safe,    signup_path,    class: "pp-button" %>

    </div>

    <h1>Welcome to Paradox Parkway</h1>

    <div id="textCarousel" class="carousel slide" data-ride="carousel" data-interval="7000">
      <div class="carousel-inner" role="listbox">
        <% @welcomeText.shuffle.each_with_index do |text, index| %>
          <div class="item funny <% if index == 0 %> active <% end %>">
            <h4><%= text %></h4>
          </div>
        <% end %>
      </div>
    </div>

    <div class="section" style="margin-top: 30px;">
      <h3>
        Paradox Parkway is your first and last stop for mind-bending fun --<br>
        Whether it's illusions, delusions, or plain ol' confusion -- we're here for you!<br>
        We're just getting started, but we've already got a lot of data to explore...<br>
        Check it out -- we welcome all comments and suggestions!<br>
      </h3>
    </div>
    <!-- <div id="talkbubble">HI</div> -->

  </div>
  
</div>
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 text-center">
    <div class="section-tab" >
      <h2 >Today In Time: <%=@today.strftime("%B #{@today.day.ordinalize}, %Y")%></h2>
    </div>
  </div>  
</div>

<!-- ///////////////////// TODAY IN TIME SECTION ///////////////////// -->

  <div class="section">
    <% unless @tits.nil? %>
      <div id="eventCarousel" class="carousel slide" data-ride="carousel" data-interval="6000" data-pause="hover">
        <div class="carousel-inner" role="listbox">
          <% @tits.shuffle.each_with_index do |tit, index| %>
            <div class="item <% if index == 0 %> active <% end %>">
              <%= render partial: "tit", object: tit %>
            </div>
          <% end %>
        </div>

      <!-- Left and right TIT controls -->

        <a class="left carousel-control" href="#eventCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#eventCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>
  </div> <!-- End of Section -->

<!--- //////////////// MY VIDEOS SECTION ///////////////////// -->

  <!-- ////////////  HEADER ///////////////////-->
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10 text-center">
      <div class="section-tab" >
        <h2 >Movie Montages!</h2>
      </div>
    </div>  
  </div>

  <div class="section">
    <div class="row center">
      <div class="video-wrapper">
        <iframe src="http://player.vimeo.com/video/<%= @montages.first["id"] %>"
                
                webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="">
        </iframe>
      </div>
      <div class="row center">
        <div class="video-textbox">
          <h4 id="vid-description"> <%= @montages.first["description"]%></h4>
        </div>
      </div>
      <div class="row center">
        <% @montages.each do |video| %>
          <%= image_tag video["thumbnail_medium"], class: "video-thumb", id: video["id"], 
                                                   alt: video["description"] %>
        <% end %>
      </div>
    </div>
    
  </div> <!-- End of Section -->

  <!-- /////////////////////  TAGLINE SECTION /////////////////////////-->
    
  <!-- ////////////  HEADER ///////////////////-->
  <div class="row">
    <div class="col-sm-offset-1 col-sm-10 text-center">
      <div class="section-tab" >
        <h2 >Tagline Trivia!</h2>
      </div>
    </div>  
  </div>

  <div class="section">

  <%= render :partial => "tagline"%>
    <!-- <div id="balls">
      <div class="sk-folding-cube">
        <div class="sk-cube1 sk-cube"></div>
        <div class="sk-cube2 sk-cube"></div>
        <div class="sk-cube4 sk-cube"></div>
        <div class="sk-cube3 sk-cube"></div>
      </div>
    </div> -->
    
  </div> <!-- End of Section -->

app/views/static_pages/paradox_news.erb
NEWS

app/views/static_pages/paradoxes.html.erb
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th width="25%">Source</th>
      <th width="73%">Line</th>
    </tr>
  </thead>
  <tbody>
    <% @doxes.each do |paradox| %>
      <tr>
      	<td><%= dox.paradox_name %></td>
      	<td><%= dox.brief %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
</div>

app/views/static_pages/tits.html.erb
<% (Date.today..Date.today + 3.days).each do |date| %>
  <h3><%= date.strftime("%B #{date.day.ordinalize}")%></h3>
    <!-- All Titles for this date -->
    <h4>Titles</h4>
	<% Title.where("release_month = ? and release_day = ?", date.mon.to_i, date.day.to_i).each do |title| %>
	  <div class="event-entry">
	  	<div class="row">
	  	  <div class="col-xs-3">
	  	    <% if title.series_index.nil? || title.series_index.blank? %>

            <%= link_to cl_image_tag("Titles/" + title.title_index.to_s + ".png", :class => "event-index-photo", :alt => title.title, :default_image => "Titles:10000.png"), title_path(title.id) %>

          <% else %>

            <%= link_to cl_image_tag("Titles/" + title.series_index.to_s + ".png", :class => "event-index-photo", :alt => title.title, :default_image => "Titles:10000.png"), title_path(title.id) %>

          <% end %>

          <%= cl_image_tag("People/" + title.people_index.to_s + ".png", :class=>"event-index-photo", :default_image => "People:40000.png") %>  

	  	  </div>
          <div class="col-xs-8 col-xs-offset-1">
      	    <h4>
                Title:        <%= title.title%>        | Title Index:  <%= title.title_index%>  | <br>
      	        Series Index: <%= title.series_index%> | People Index: <%= title.people_index%> | <br> 
      	        Release Date: <%= title.release_date%> | <%= link_to "EDIT", edit_title_path(title.id) %> 
            </h4>
      	    <br>
      	    <!-- Is the release message missing? -->
            <% if title.release_msg.nil? %>
              <div style="color:orange"><strong>Release Message:</strong> <%= title.release_msg%></div>
            <% else %>
              <h5>Release Message: <%= title.release_msg%> </h5>
            <% end %>

            <% titlePerson = Person.find_by people_index: title.people_index %>
            <% if titlePerson.nil? %>
              <div style="color:yellow"><strong>Person Path no good.</strong></div>
            <% end %>

          </div>
        </div>
	  </div>
	<% end %>
	<!-- All Births for this date -->
  <h4>Births</h4>
	<% Person.where("birth_month = ? and birth_day = ?", date.mon.to_i, date.day.to_i).each do |birth| %>
	  <div class="event-entry">
	  	<div class="row">
	  	  <div class="col-xs-3">
	  	    <%= cl_image_tag("People/" + birth.people_index.to_s + ".png", :class=>"event-index-photo", :default_image => "People:40000.png") %>	
          <%= cl_image_tag("Titles/" + birth.title_index.to_s + ".png", :class=>"event-index-photo", :default_image => "Titles:10000.png") %> 
	  	  </div>
          <div class="col-xs-8 col-xs-offset-1">
      	    <h4>
                Name:        <%= birth.full_name%>   | People Index: <%= birth.people_index%> | <br>
      	        Title Index: <%= birth.title_index%> | Birth Date:   <%= birth.birth_date%>   | <br>
      	        <%= link_to "EDIT", edit_person_path(birth.id) %> 
            </h4>

            <% if !Title.exists?(title_index: birth.title_index) %>
              <h5 style="color:red "> <%= birth.title_index %> does not have a title record in the DB !!!</h5>
            <% end %>

          </div>
        </div>
	  </div>
	<% end %>
	<!-- All Deaths for this date -->
  <h4>Deaths</h4>
    <% Person.where("death_month = ? and death_day = ?", date.mon.to_i, date.day.to_i).each do |death| %>
	  <div class="event-entry">
	  	<div class="row">
	  	  <div class="col-xs-3">
	  	    <%= cl_image_tag("People/" + death.people_index.to_s + ".png", :class=>"event-index-photo", :default_image => "People:40000.png") %>	
          <%= cl_image_tag("Titles/" + death.title_index.to_s + ".png", :class=>"event-index-photo", :default_image => "Titles:10000.png") %> 
	  	  </div>
          <div class="col-xs-8 col-xs-offset-1">
      	    <h4>
                 Name:        <%= death.full_name%>   | People Index: <%= death.people_index%> | <br>
      	         Title Index: <%= death.title_index%> | Death Date:   <%= death.death_date%>   | <br>
      	         <%= link_to "EDIT", edit_person_path(death.id) %> 
            </h4>

            <% if !Title.exists?(title_index: death.title_index) %>
              <h5 style="color:red "> <%= death.title_index %> does not have a title record in the DB !!!</h5>
            <% end %>

          </div>
        </div>
	  </div>
	<% end %>
<% end %>

app/views/static_pages/uploads.html.erb
<%= flash[:notice] %>

<h3>Import a Paradox CSV File</h3>
<%= form_tag import_doxes_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import Paradoxes CSV" %>
<% end %>

<h3>Import a People CSV File</h3>
<%= form_tag import_people_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import People CSV" %>
<% end %>

<h3>Import a Titles CSV File</h3>
<%= form_tag import_titles_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import Titles CSV" %>
<% end %>

<h3>Import a Taglines CSV File</h3>
<%= form_tag import_taglines_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import Tagline CSV" %>
<% end %>

<h3><strong>Import a Events CSV File</strong></h3>
<%= form_tag import_events_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import Events CSV" %>
<% end %>