config/routes.rb
Rails.application.routes.draw do

  get 'events/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root                       'static_pages#index'
  get    'paradox_people' => 'static_pages#paradox_people'
  get    'uploads'        => 'static_pages#uploads'
  get    'paradox_news'   => 'static_pages#paradox_news'
  get    'about'          => 'static_pages#about'
  get    'tits'           => 'static_pages#tits'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :taglines, :doxes, :titles, :people, :events, :blogposts do
    collection { post :import }
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  require 'csv'
  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'windows-1251:utf-8') do |row|

      event_hash = row.to_hash # exclude the price field
      event = Event.where(event_index: event_hash["event_index"])

      if event.count == 1
        event.first.update_attributes(event_hash)
      else
        Event.create!(event_hash)
      end # end if !product.nil?
    end # end CSV.foreach
  end # end self.import(file)
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :admin_user,     only: [:destroy, :update, :patch]

  def index
    @events = Event.all
      if params[:search]
    	@events = Event.search(params[:search], params[:page])
  	  else
    	@events = Event.paginate(page: params[:page])
  	end
  end 

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "event deleted"
    redirect_to events_url
  end

  def import
  	Event.import(params[:file])
  	redirect_to events_url, notice: "events File Imported."
  end


  def update
    @event = Event.find(params[:id])
      
    if @event.update(event_params)
        flash[:success] = "Entry updated!"
      redirect_to @event
    else
      render 'edit'
    end
  end
 
  private
    def event_params
      params.require(:event).permit(:event_year, :event_century, :event_month, :event_day, :event_minute, :event_second, :event_period, 
      								:event_to, :event_location, :event_historical_event, :event_person, :event_blurb)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="container-fluid dox-entry">
  <div class="row">
      <div class="row">
        <div class="col-xs-3"><p> <strong>Event Year</strong> <%= event.event_year %> </p></div>
        <div class="col-xs-3"><p> <strong>To:</strong> <%= event.event_to %> </p></div>
        <div class="col-xs-3"><p> <strong>Location:</strong> <%= event.event_location %> </p></div>
      </div>
      <% if !current_user.nil? && current_user.admin? %>
        <div class="col-xs-12 admin-box">
          <strong>Event Index:</strong> <%= event.event_index%>
          <br>
          <strong><%= link_to "DELETE", event, method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %></strong>    |  <strong><%= link_to "EDIT", edit_event_path(event.id) %></strong></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<% @events.order("event_year ASC").each do |event| %>
  <%= render partial: "event", object: event %>
<% end %>