config/routes.rb
Rails.application.routes.draw do

  get 'events/index'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root                       'static_pages#index'
  get    'paradox_people' => 'static_pages#paradox_people'
  get    'uploads'        => 'static_pages#uploads'
  get    'paradox_news'   => 'static_pages#paradox_news'
  get    'about'          => 'static_pages#about'
  get    'tits'           => 'static_pages#tits'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :taglines, :doxes, :titles, :people, :events, :blogposts do
    collection { post :import }
  end

end

app/models/dox.rb
class Dox < ActiveRecord::Base
  require 'csv'

  def self.search(search, page)
    order('dox').where("cast(paradox_index as text) ILIKE ? OR cast(discovery_date as text) ILIKE ? OR paradox_name ILIKE ? OR paradox ILIKE ? OR 
                        brief ILIKE ? OR full_description ILIKE ? OR owner ILIKE ? OR example ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%",
                         "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%").paginate(page: page, per_page: 20)
  end


  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: 'windows-1251:utf-8') do |row|

      dox_hash = row.to_hash # exclude the price field
      dox = Dox.where(paradox_index: dox_hash["paradox_index"])

      if dox.count == 1
        dox.first.update_attributes(dox_hash)
      else
        Dox.create!(dox_hash)
      end # end if !product.nil?
    end # end CSV.foreach
  end # end self.import(file)
end

app/controllers/doxes_controller.rb
class DoxesController < ApplicationController
  def index
   	@doxes = Dox.all
      if params[:search]
    	@doxes = Dox.search(params[:search], params[:page])
  	  else
    	@doxes = Dox.all.paginate(page: params[:page], :per_page => 15)
  	end
  end 

  def destroy
    Dox.find(params[:id]).destroy
    flash[:success] = "Paradox deleted"
    redirect_to doxes_url
  end

  def import
  	Dox.import(params[:file])
  	redirect_to doxes_url, notice: "Paradoxes File Imported."
  end
end

app/helpers/doxes_helper.rb
module DoxesHelper
end

app/views/doxes/index.html.erb
<%= form_tag(doxes_path, :method => "get", :class => "inline", :style => "margin-bottom: 15px;", id: "search-form") do %>
  <div class="input-group">
    <div class="input-group-addon">
      <% if @doxes.count == 1 %>
        <strong><%= @doxes.count %></strong> total entry.
      <% else %>
        <strong><%= @doxes.count %></strong> total entries.
      <% end %>
    </div>
    <%= text_field_tag :search, params[:search],:class => "form-control", placeholder: "Search Paradoxes", autofocus: "autofocus" %>
    <div class="input-group-btn">
      <%= submit_tag "Search", class: "btn btn-primary" %>  
    </div>
  </div>
<% end %>

<%= will_paginate %>

<% @doxes.each do |dox| %>
<div class="container-fluid dox-entry">
  <div class="row">
    <div class="col-xs-2"><h5> Paradox Name </h5></div>
    <div class="col-xs-10"><h4> <%= dox.paradox_name %> </h4></div>
  </div>
  <div class="row">
    <div class="col-xs-2"><h5> Paradox Brief </h5></div>
    <div class="col-xs-10"><p> <%= dox.brief %> </p></div>
  </div>
  <div class="row">
    <div class="col-xs-2"><h5> Full Description </h5></div>
    <div class="col-xs-10"><p> <%= dox.full_description %> </p></div>
  </div>
  <div class="row">
    <div class="col-xs-2"><h5> Discovery Date </h5></div>
    <div class="col-xs-10"><p> <%= dox.discovery_date %> </p></div>
  </div>
  <div class="row">
    <div class="col-xs-2"><h5> Owner </h5></div>
    <div class="col-xs-10"><p> <%= dox.owner %> </p></div>
  </div>
  <div class="row">
    <div class="col-xs-2"><h5> Example </h5></div>
    <div class="col-xs-10"><p> <%= dox.example %> </p></div>
  </div>
  <% if !current_user.nil? && current_user.admin? %>
    <div class="admin-box col-xs-12">
      <p>  <strong><%= link_to "DELETE", dox, method: :delete, data: { confirm: "Are you sure you want to delete this paradox?" } %></strong>    |  <strong><%= link_to "EDIT", edit_dox_path(dox.id) %></strong></p>
    </div>
  <% end %>
</div>
<% end %>

<%= will_paginate %>